### ISSUE TITLE
This textobj plugin is invalid now?

### ISSUE THREAD

**Issue by Vesion** [kana/vim-textobj-line#4]
This textobj-line plugin is invalid now. I checked the code and found that the ''select-a-function" and "select-i-function" in plugin/textobj/line.vim are surrounded with * for unknown reason, resulting in textobj#user#plugin function finding invalid keys. Remove the asterisks to put this plugin on the working way.

**Comment by kana** [comment]
Do you have any problem? It still works for me.

**Comment by Vesion** [comment]
Sorry, perhaps my description was not very clear. This plugin cannot work for me before. So I changed the code in plugin/textobj/line.vim from

call textobj#user#plugin('line', {
\      '-': {
\        'select-a': 'al', '*select-a-function*': 'textobj#line#select_a',
\        'select-i': 'il', '*select-i-function*': 'textobj#line#select_i',
\      },
\    })

to

call textobj#user#plugin('line', {
\      '-': {
\        'select-a': 'al', 'select-a-function': 'textobj#line#select_a',
\        'select-i': 'il', 'select-i-function': 'textobj#line#select_i',
\      },
\    })

(I removed the asterisks.)
so that it woks well now. I have no idea why were asterisks there before.

**Comment by Vesion** [comment]
Sorry, perhaps my description was not very clear. This plugin cannot work for me before. So I changed the code in plugin/textobj/line.vim from

call textobj#user#plugin('line', {
\ '-': {
\ 'select-a': 'al', '*select-a-function*': 'textobj#line#select_a',
\ 'select-i': 'il', '*select-i-function*': 'textobj#line#select_i',
\ },
\ })

to

call textobj#user#plugin('line', {
\ '-': {
\ 'select-a': 'al', 'select-a-function': 'textobj#line#select_a',
\ 'select-i': 'il', 'select-i-function': 'textobj#line#select_i',
\ },
\ })

(I removed the asterisks.)
so that it woks well now. I have no idea why were asterisks there before.

**Comment by Vesion** [comment]
Sorry, perhaps my description was not very clear. This plugin cannot work for me before. So I changed the code in plugin/textobj/line.vim from

call textobj#user#plugin('line', {
\ '-': {
\ 'select-a': 'al', '`\*select-a-function\*`': 'textobj#line#select_a',
\ 'select-i': 'il', '`\*select-i-function\*`': 'textobj#line#select_i',
\ },
\ })

to

call textobj#user#plugin('line', {
\ '-': {
\ 'select-a': 'al', '`select-a-function`': 'textobj#line#select_a',
\ 'select-i': 'il', '`select-i-function`': 'textobj#line#select_i',
\ },
\ })

(I removed the asterisks.)
so that it woks well now. I have no idea why were asterisks there before.

**Comment by Vesion** [comment]
Sorry, perhaps my description was not very clear. This plugin cannot work for me before. So I changed the code in plugin/textobj/line.vim from

call textobj#user#plugin('line', {
\ '-': {
\ 'select-a': 'al', '\*select-a-function\*': 'textobj#line#select_a',
\ 'select-i': 'il', '\*select-i-function\*': 'textobj#line#select_i',
\ },
\ })

to

call textobj#user#plugin('line', {
\ '-': {
\ 'select-a': 'al', 'select-a-function': 'textobj#line#select_a',
\ 'select-i': 'il', 'select-i-function': 'textobj#line#select_i',
\ },
\ })

(I removed the asterisks.)
so that it woks well now. I have no idea why were asterisks there before.

**Comment by kana** [comment]
[The asterisks are used in old versions of vim-textobj-user, but they are still available at the moment.](https://github.com/kana/vim-textobj-user/blob/master/doc/textobj-user.txt#L341-L353)  So it's strange that the plugin did not work on your environment.  Would you mind pasting the error message you saw and what versions of plugins you used?  Anyway, I'll update the old names later.

**Comment by kana** [comment]
I've fixed.  https://github.com/kana/vim-textobj-line/commit/7905467f977b0bbd4d133561ce5a9cbf5d6d1f5b
