### ISSUE TITLE
Marks '< and '> being clobbered

### ISSUE THREAD

**Issue by Asheq** [kana/vim-textobj-line#6]
First off, I love this text object. I use `yil` (yank in line)  all the time.

I'm experiencing a minor problem, however. When I invoke `yil`, it overwrites the '< and '> marks. These marks are standard marks that indicate the first and last character of the previously visually-selected area. I don't expect `yil` to change these marks. I think `yil` should behave like built-in commands like `yiw`, which leave these marks alone.

I imagine that the plugin is visually selecting the text object in the background. Is there any way to do that without the side effect of changing '< and '>? Maybe by saving them and restoring them before the function completes?

Thanks

**Comment by kana** [comment]
Thank you for the report. I'll look into later.

**Comment by kana** [comment]
I've looked into the problem.  It is a common problem for all vim-textobj-user based plugins. I'll try to fix later.

**Comment by kana** [comment]
I've fixed the problem.  Please update vim-textobj-user.

**Comment by Asheq** [comment]
Looks like it's working for me. Thanks for the prompt fix!
